name:                Ch07
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/Ch07#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - bytestring
  - text
  - vector
  - attoparsec
  - split
  - aeson
  - time
  - lens
  - mtl
  - operational
  - pipes

executables:
  Ch07:
    source-dirs:      src
    main:             Main.hs
